### PR TITLE
Add `eslint-plugin-sort-requires`

### PR DESCRIPTION
**Pull request by nunofgs**
Adds the [eslint-plugin-sort-requires](https://github.com/kentor/eslint-plugin-sort-requires) plugin.

### CODE REVIEW

**Comment by kurayama** [comment]
Aren't there any other plugins which are case sensitive and allow lines with destructuring to be required first?

**Comment by nunofgs** [comment]
> Aren't there any other plugins which are case sensitive and allow lines with destructuring to be required first?

The only one of a decent quality is [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import), although it currently doesn't support alphabetical sorting (there's a PR for it and I have it working locally) and there is no option to influence the order to include destructuring.

**Comment by ruimarinho** [comment]
That last plugin is quite popular. I wonder if alphabetical sorting would be something they'd be interested in?

**Comment by nunofgs** [comment]
@ruimarinho As I mentioned, that plugin has a PR that allows secondary sorting (ie: per filename) which is not what we really want 😢 

Also, that repo has 26 open PRs and seems unmaintained.

**Comment by ruimarinho** [comment]
Considering all that, I would move forward with the basic implementation which is actually closer to what we would like to do (primary sorting) and switch implementations when we feel comfortable enough with `eslint-plugin-import`.

**Pull request closed without merging**
