### PR TITLE
Use string for severity in config

### PR DESCRIPTION
**Pull request by ruimarinho**
Improves config readability.

### CODE REVIEW

**Comment by ruimarinho** [comment]
@ruiquelhas can you take a look at the open PRs?

**Comment by ruiquelhas** [comment]
@ruimarinho please rebase.

**Comment by ruimarinho** [comment]
@ruiquelhas this should have been merged first to reduce conflicts.

**Comment by ruimarinho** [comment]
Rebased.

**Comment by ruiquelhas** [comment]
The first time was because I couldn't even run `npm install`. This time I just screwed up. Can you please rebase again.

Sorry. :cry:

**Comment by ruimarinho** [comment]
Done.

**Pull request merged**
