### PR TITLE
Add plugin to sort class members

### LINKED ISSUE #25: Add eslint-plugin-sort-class-members
Allows to set sorting rules for classes.

### PR DESCRIPTION
**Pull request by ruimarinho**
Tagging this as major since it requires installing a plugin.

Closes #25.

### CODE REVIEW

**Comment by fixe** [comment]
I like this.

**Comment by ruimarinho** [comment]
@ruiquelhas can you bundle this with import order sort?

**Comment by ruiquelhas** [comment]
@ruimarinho sure, can you please rebase?

**Comment by ruimarinho** [comment]
Rebased.

**Pull request merged**
